name: Scala Steward

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3.1.0
      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - id: scala_steward
        name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.20.0
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          repos-file: 'repos.md'
          sign-commits: true
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name: ${{ steps.import_gpg.outputs.name }}
